name       : kanagram
version    : 16.12.3
release    : 2
source     :
    - http://download.kde.org/stable/applications/16.12.3/src/kanagram-16.12.3.tar.xz : 87f04c450b2e1d0c39792e3cba2940fb42afefa5226e575f19031ec77b9f70a0
license    : GPL-2.0
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - kinit
    - qt5-quickcontrols
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
