name       : kanagram
version    : 18.04.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kanagram-18.04.2.tar.xz : 7d687bda6187a27af4d651128fad20bf14d2e73b7ccc4368840ba603ba8d8926
license    : GPL-2.0
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - qt5-multimedia
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
