name       : kanagram
version    : 18.08.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kanagram-18.08.3.tar.xz : c38e835569c8414bfae76d60dee8d35145389c9fdad5db54be9c4a6255553e18
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - qt5-multimedia
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
