name       : kanagram
version    : 16.12.1
release    : 1
source     :
    - http://download.kde.org/stable/applications/16.12.1/src/kanagram-16.12.1.tar.xz : f01406cb7836eb995be76769ee19dec44d29054c9b47a47c887bbd98c1562d67
license    : GPL-2.0
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - kinit
    - qt5-quickcontrols
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
