name       : kanagram
version    : 21.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kanagram-21.04.1.tar.xz : cb7e78020955f8e5f385ca19e3029ae557821030f3fb9936bc24706a1d340dc5
homepage   : https://kde.org/applications/education/org.kde.kanagram
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5TextToSpeech)
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove doc
    rm -rf $installdir/usr/share/doc
