name       : kanagram
version    : 17.12.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/kanagram-17.12.0.tar.xz : 432dfc033d2b1873433eeb83e149721d6c9c44e731aaec296254ca264f136297
license    : GPL-2.0
component  : games.puzzle
optimize   : lto
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - qt5-multimedia
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
