name       : kanagram
version    : 19.04.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/kanagram-19.04.0.tar.xz : dda3ce8211957e016521597a923de92d261e32c31ebf84faa697bd26cf16647c
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5TextToSpeech)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - qt5-multimedia
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
