name       : kanagram
version    : 17.04.0
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kanagram-17.04.0.tar.xz : f1803dee84e2ecd79599daa2d5063258fc4c41f6112876df15d26ec4b42c9364
license    : GPL-2.0
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(gl)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - kinit
    - qt5-quickcontrols
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
