name       : kanagram
version    : 19.12.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kanagram-19.12.3.tar.xz : 441cae90d3b70dbef40bebbcf1325fa06e0df174a3f961b4b117a5fa1b40d6e3
homepage   : https://kde.org/applications/education/org.kde.kanagram
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Letter Order Game
description: |
    Kanagram is a game based on anagrams of words: the puzzle is solved
    when the letters of the scrambled word are put back in the correct
    order.
    There is no limit on either time taken, or the amount of attempts
    to solve the word.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5TextToSpeech)
    - extra-cmake-modules
    - kcrash-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - libkeduvocdocument-devel
    - sonnet-devel
rundeps    :
    - qt5-multimedia
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
